#!/bin/bash

echo "=========================================="
echo "  Simple Node Test - Run on Each Machine"
echo "=========================================="
echo ""

# Get my IP
MY_IP=$(hostname -I | awk '{print $1}')
echo "This machine's IP: $MY_IP"
echo ""

# Instructions
echo "STEP 1: Start this node"
echo "----------------------------------------"
echo "Run this command on THIS machine:"
echo ""
echo "cargo run --release --bin cloud-node <NODE_ID> 0.0.0.0:800<NODE_ID> <PEER1_IP>:800<ID>,<PEER2_IP>:800<ID>"
echo ""
echo "Example for Node 1:"
echo "cargo run --release --bin cloud-node 1 0.0.0.0:8001 $MY_IP:8002,$MY_IP:8003"
echo ""
echo ""

echo "STEP 2: Check if it's working"
echo "----------------------------------------"
echo "After 15-30 seconds, look for these in the logs:"
echo ""
echo "✅ GOOD - Multiple nodes in election:"
echo "   All node loads:"
echo "     Node 1: 0.50"
echo "     Node 2: 0.50  <-- Multiple nodes!"
echo "     Node 3: 0.50"
echo ""
echo "❌ BAD - Only one node:"
echo "   All node loads:"
echo "     Node 1: 0.50  <-- Only YOUR node = not working!"
echo ""
echo ""

echo "STEP 3: Quick Tests"
echo "----------------------------------------"
echo "Test 1 - Check if port is open:"
echo "  sudo ss -ulnp | grep 800"
echo ""
echo "Test 2 - Watch network traffic:"
echo "  sudo tcpdump -i any udp port 8001"
echo ""
echo "Test 3 - Send test message from another machine:"
echo "  echo '{\"LoadQuery\":{\"from_node\":99}}' | nc -u $MY_IP 8001"
echo ""
echo ""

echo "TROUBLESHOOTING"
echo "----------------------------------------"
echo "If nodes can't see each other:"
echo "  1. Use WiFi IPs (not Ethernet 10.x.x.x IPs)"
echo "  2. Check firewall: sudo ufw status"
echo "  3. Test ping: ping <OTHER_NODE_IP>"
echo "  4. All machines on same WiFi network"
echo ""
