#!/bin/bash
# Helper script to show you exactly what to run

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║  STEP-BY-STEP INSTRUCTIONS                                       ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "You need TWO terminals open:"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 1: Start the Server                                    │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "Run this command:"
echo ""
echo "  cd /home/khoulykid@auc.egy/Desktop/Distributed-Image-Sharing-Cloud"
echo "  cargo run --release --bin cloud-node -- 1 127.0.0.1:8001"
echo ""
echo "Wait until you see: \"[Node 1] Listening on 127.0.0.1:8001 (UDP)\""
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 2: Run the Test                                        │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "Run this command:"
echo ""
echo "  cd /home/khoulykid@auc.egy/Desktop/Distributed-Image-Sharing-Cloud/single_img_testing"
echo "  ./simple_run.sh 127.0.0.1:8001"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ WHAT YOU'LL SEE                                                  │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "  1. Original image opens (clear, readable)"
echo "  2. Encrypted image opens (scrambled noise)"
echo "  3. Decrypted image opens (clear again - restored!)"
echo "  4. Terminal shows success summary"
echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║  READY TO START?                                                 ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Press Ctrl+C to exit this helper"
echo "Then follow the instructions above!"
echo ""
